version: 2
updates:
  - package-ecosystem: npm
    directory: /cloud/frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /pi/frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: uv
    directory: /cloud/backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: uv
    directory: /pi/backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: uv
    directory: /cloud/hosted-pi-manager
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
