/** Curated MDI SVG paths used by the cloud admin UI (mdi-* name → path). */
import {
  mdiAccount,
  mdiAlert,
  mdiAlertCircleOutline,
  mdiArrowLeft,
  mdiBriefcase,
  mdiBriefcaseEdit,
  mdiCalendar,
  mdiCalendarMonth,
  mdiCalendarPlus,
  mdiChevronLeft,
  mdiCardAccountDetails,
  mdiCellphone,
  mdiChartBar,
  mdiChartLine,
  mdiCheck,
  mdiCheckCircle,
  mdiCheckCircleOutline,
  mdiChevronDown,
  mdiChevronRight,
  mdiCircle,
  mdiCircleOutline,
  mdiClose,
  mdiCloudSync,
  mdiCog,
  mdiCreditCardOutline,
  mdiCreditCardWireless,
  mdiDelete,
  mdiDevices,
  mdiEarth,
  mdiEye,
  mdiEyeOff,
  mdiFileDocumentOutline,
  mdiFolder,
  mdiFoodVariant,
  mdiHelpCircleOutline,
  mdiInformation,
  mdiLogout,
  mdiMagnify,
  mdiMenu,
  mdiMonitor,
  mdiOfficeBuilding,
  mdiPercent,
  mdiPlayCircle,
  mdiPrinter,
  mdiRefresh,
  mdiRouterWireless,
  mdiServer,
  mdiTablet,
  mdiTagMultiple,
  mdiWeatherNight,
  mdiWhiteBalanceSunny,
  mdiWifi,
} from '@mdi/js'

export const mdiIconPaths: Record<string, string> = {
  'mdi-account': mdiAccount,
  'mdi-alert': mdiAlert,
  'mdi-alert-circle-outline': mdiAlertCircleOutline,
  'mdi-arrow-left': mdiArrowLeft,
  'mdi-briefcase': mdiBriefcase,
  'mdi-briefcase-edit': mdiBriefcaseEdit,
  'mdi-calendar': mdiCalendar,
  'mdi-calendar-month': mdiCalendarMonth,
  'mdi-calendar-plus': mdiCalendarPlus,
  'mdi-card-account-details': mdiCardAccountDetails,
  'mdi-cellphone': mdiCellphone,
  'mdi-chart-bar': mdiChartBar,
  'mdi-chart-line': mdiChartLine,
  'mdi-check': mdiCheck,
  'mdi-check-circle': mdiCheckCircle,
  'mdi-check-circle-outline': mdiCheckCircleOutline,
  'mdi-chevron-down': mdiChevronDown,
  'mdi-chevron-left': mdiChevronLeft,
  'mdi-chevron-right': mdiChevronRight,
  'mdi-circle': mdiCircle,
  'mdi-circle-outline': mdiCircleOutline,
  'mdi-close': mdiClose,
  'mdi-cloud-sync': mdiCloudSync,
  'mdi-cog': mdiCog,
  'mdi-credit-card-outline': mdiCreditCardOutline,
  'mdi-credit-card-wireless': mdiCreditCardWireless,
  'mdi-delete': mdiDelete,
  'mdi-devices': mdiDevices,
  'mdi-earth': mdiEarth,
  'mdi-eye': mdiEye,
  'mdi-eye-off': mdiEyeOff,
  'mdi-file-document-outline': mdiFileDocumentOutline,
  'mdi-folder': mdiFolder,
  'mdi-food-variant': mdiFoodVariant,
  'mdi-help-circle-outline': mdiHelpCircleOutline,
  'mdi-information': mdiInformation,
  'mdi-logout': mdiLogout,
  'mdi-magnify': mdiMagnify,
  'mdi-menu': mdiMenu,
  'mdi-monitor': mdiMonitor,
  'mdi-office-building': mdiOfficeBuilding,
  'mdi-percent': mdiPercent,
  'mdi-play-circle': mdiPlayCircle,
  'mdi-printer': mdiPrinter,
  'mdi-refresh': mdiRefresh,
  'mdi-router-wireless': mdiRouterWireless,
  'mdi-server': mdiServer,
  'mdi-tablet': mdiTablet,
  'mdi-tag-multiple': mdiTagMultiple,
  'mdi-weather-night': mdiWeatherNight,
  'mdi-white-balance-sunny': mdiWhiteBalanceSunny,
  'mdi-wifi': mdiWifi,
}

export function resolveMdiIconPath(name: string): string | undefined {
  return mdiIconPaths[name]
}

export function listUsedMdiIconNames(): string[] {
  return Object.keys(mdiIconPaths).sort()
}
