import { computed } from 'vue'
import {
  activeTableNumber,
  addCartLine,
  addVoucherCartLine,
  cartLineLabel,
  additionsSignature,
  articleName,
  availableAdditionQty,
  availableQty,
  cartCount,
  cartDiscountCents,
  cartGrossCents,
  cartLines,
  cartSubtotalCents,
  cartTotalCents,
  clearCart,
  orderDiscount,
  setOrderDiscount,
  decrementCartLine,
  getArticle,
  removeCartLine,
  updateCartLine,
} from '../store'

export function useCart() {
  return {
    cartLines: computed(() => cartLines.value),
    lines: computed(() => cartLines.value),
    cartCount,
    cartSubtotalCents,
    cartGrossCents,
    cartDiscountCents,
    cartTotalCents,
    totalCents: cartTotalCents,
    orderDiscount,
    setOrderDiscount,
    activeTableNumber,
    addCartLine,
    addVoucherCartLine,
    cartLineLabel,
    removeCartLine,
    clearCart,
    decrementCartLine,
    updateCartLine,
    availableQty,
    availableAdditionQty,
    getArticle,
    articleName,
    additionsSignature,
  }
}
