"""Automatic appliance names for servers (Greek gods) and printers (capital cities)."""

import random
from typing import Iterable

from sqlalchemy.orm import Session

from .models import Appliance

GREEK_GODS = [
    # Olympians and major deities
    "Zeus",
    "Hera",
    "Poseidon",
    "Demeter",
    "Athena",
    "Apollo",
    "Artemis",
    "Ares",
    "Aphrodite",
    "Hephaestus",
    "Hermes",
    "Hestia",
    "Dionysus",
    "Persephone",
    "Hades",
    # Titans and primordials
    "Chronos",
    "Rhea",
    "Oceanus",
    "Tethys",
    "Hyperion",
    "Theia",
    "Coeus",
    "Phoebe",
    "Crius",
    "Iapetus",
    "Themis",
    "Mnemosyne",
    "Atlas",
    "Prometheus",
    "Epimetheus",
    "Gaia",
    "Uranus",
    "Pontus",
    "Nyx",
    "Erebus",
    "Aether",
    "Hemera",
    "Chaos",
    "Tartarus",
    # Well-known gods and spirits
    "Nike",
    "Eros",
    "Helios",
    "Selene",
    "Eos",
    "Nemesis",
    "Iris",
    "Pan",
    "Hecate",
    "Hypnos",
    "Thanatos",
    "Morpheus",
    "Triton",
    "Asclepius",
    "Hebe",
    "Ganymede",
    "Tyche",
    "Eris",
    "Harmonia",
    "Leto",
    "Styx",
    "Charon",
    "Enyo",
    "Deimos",
    "Phobos",
    "Ananke",
    "Adrasteia",
    "Aletheia",
    "Apate",
    "Dolos",
    "Momus",
    "Plutus",
    "Hygieia",
    "Panacea",
    "Pheme",
    "Peitho",
    "Sophrosyne",
    "Zelus",
    "Kratos",
    "Bia",
    "Astraea",
    "Dike",
    "Eunomia",
    # Fates and seasons
    "Clotho",
    "Lachesis",
    "Atropos",
    "Horae",
    "Carpo",
    "Thallo",
    "Auxo",
    # Muses
    "Calliope",
    "Clio",
    "Erato",
    "Euterpe",
    "Melpomene",
    "Polyhymnia",
    "Terpsichore",
    "Thalia",
    "Urania",
    # Winds and sea
    "Aeolus",
    "Boreas",
    "Zephyrus",
    "Notus",
    "Eurus",
    "Nereus",
    "Proteus",
    "Glaucus",
    "Amphitrite",
    "Ceto",
    "Phorcys",
    "Thaumas",
    # Underworld and chthonic
    "Melinoe",
    "Macaria",
    "Zagreus",
    "Iacchus",
    "Erinyes",
    "Megaera",
    "Alecto",
    "Tisiphone",
    "Cerberus",
    "Orpheus",
    # Heroes and demigods often venerated
    "Heracles",
    "Perseus",
    "Theseus",
    "Achilles",
    "Orion",
    "Bellerophon",
    "Jason",
    "Atalanta",
    "Castor",
    "Pollux",
    "Helen",
    "Cassandra",
    "Medea",
    "Psyche",
    "Adonis",
    "Cybele",
    "Attis",
    "Priapus",
    "Silenus",
    "Midas",
    "Sisyphus",
    "Tantalus",
    "Ixion",
    "Phaethon",
    "Pandora",
    "Arachne",
    "Daedalus",
    "Icarus",
    "Antigone",
    "Oedipus",
    "Electra",
    "Orestes",
    "Agamemnon",
    "Menelaus",
    "Odysseus",
    "Penelope",
    "Circe",
    "Calypso",
    "Scylla",
    "Charybdis",
    "Sirens",
    "Lamia",
    "Empusa",
    "Gorgon",
    "Medusa",
    "Chimera",
    "Typhon",
    "Python",
    "Pasithea",
    "Britomartis",
    "Despoina",
    "Ariadne",
    "Hippolyta",
    "Alcestis",
    "Semele",
    "Europa",
    "Io",
    "Danae",
    "Leda",
    "Alcmene",
    "Deianeira",
    "Andromeda",
    "Peleus",
]

CAPITAL_CITIES = [
    # Europe
    "Berlin",
    "Paris",
    "London",
    "Madrid",
    "Rome",
    "Vienna",
    "Brussels",
    "Amsterdam",
    "Warsaw",
    "Prague",
    "Budapest",
    "Stockholm",
    "Oslo",
    "Copenhagen",
    "Helsinki",
    "Dublin",
    "Lisbon",
    "Athens",
    "Bucharest",
    "Sofia",
    "Zagreb",
    "Ljubljana",
    "Bratislava",
    "Tallinn",
    "Riga",
    "Vilnius",
    "Bern",
    "Luxembourg",
    "Nicosia",
    "Valletta",
    "Minsk",
    "Chisinau",
    "Belgrade",
    "Sarajevo",
    "Podgorica",
    "Skopje",
    "Pristina",
    "Tirana",
    "Reykjavik",
    "Monaco",
    "Andorra la Vella",
    "San Marino",
    "Vatican City",
    # Asia
    "Tokyo",
    "Beijing",
    "Seoul",
    "New Delhi",
    "Islamabad",
    "Kabul",
    "Tehran",
    "Baghdad",
    "Riyadh",
    "Abu Dhabi",
    "Doha",
    "Manama",
    "Kuwait City",
    "Muscat",
    "Sanaa",
    "Amman",
    "Beirut",
    "Damascus",
    "Ankara",
    "Jerusalem",
    "Tbilisi",
    "Yerevan",
    "Baku",
    "Ashgabat",
    "Tashkent",
    "Bishkek",
    "Dushanbe",
    "Astana",
    "Ulaanbaatar",
    "Pyongyang",
    "Bangkok",
    "Hanoi",
    "Vientiane",
    "Phnom Penh",
    "Naypyidaw",
    "Kuala Lumpur",
    "Singapore",
    "Jakarta",
    "Manila",
    "Bandar Seri Begawan",
    "Dili",
    "Colombo",
    "Kathmandu",
    "Thimphu",
    "Dhaka",
    "Male",
    # Oceania
    "Canberra",
    "Wellington",
    "Port Moresby",
    "Suva",
    "Honiara",
    "Port Vila",
    "Nuku'alofa",
    "Apia",
    "Tarawa",
    "Majuro",
    "Palikir",
    # Americas
    "Washington",
    "Ottawa",
    "Mexico City",
    "Guatemala City",
    "Belmopan",
    "San Salvador",
    "Tegucigalpa",
    "Managua",
    "San Jose",
    "Panama City",
    "Havana",
    "Kingston",
    "Port-au-Prince",
    "Santo Domingo",
    "Nassau",
    "Bridgetown",
    "Port of Spain",
    "Bogota",
    "Caracas",
    "Georgetown",
    "Paramaribo",
    "Cayenne",
    "Quito",
    "Lima",
    "La Paz",
    "Sucre",
    "Brasilia",
    "Buenos Aires",
    "Asuncion",
    "Montevideo",
    "Santiago",
    # Africa
    "Cairo",
    "Rabat",
    "Algiers",
    "Tunis",
    "Tripoli",
    "Khartoum",
    "Juba",
    "Addis Ababa",
    "Nairobi",
    "Mogadishu",
    "Djibouti",
    "Asmara",
    "Kampala",
    "Kigali",
    "Gitega",
    "Dodoma",
    "Lusaka",
    "Harare",
    "Maputo",
    "Lilongwe",
    "Windhoek",
    "Gaborone",
    "Maseru",
    "Mbabane",
    "Pretoria",
    "Antananarivo",
    "Port Louis",
    "Victoria",
    "Moroni",
    "Sao Tome",
    "Praia",
    "Banjul",
    "Dakar",
    "Bamako",
    "Ouagadougou",
    "Niamey",
    "N'Djamena",
    "Bangui",
    "Kinshasa",
    "Brazzaville",
    "Libreville",
    "Malabo",
    "Yaounde",
    "Abuja",
    "Accra",
    "Lome",
    "Porto-Novo",
    "Yamoussoukro",
    "Monrovia",
    "Freetown",
    "Conakry",
    "Bissau",
    "Nouakchott",
    "Luanda",
]


def _used_names(db: Session, appliance_type: str, exclude_id: int | None) -> set[str]:
    query = db.query(Appliance.name).filter(
        Appliance.type == appliance_type,
        Appliance.name.isnot(None),
    )
    if exclude_id is not None:
        query = query.filter(Appliance.id != exclude_id)
    return {row[0] for row in query.all() if row[0]}


def _pick_from_pool(pool: Iterable[str], used: set[str]) -> str:
    available = [n for n in pool if n not in used]
    if available:
        return random.choice(available)
    # All names taken for this type — append numeric suffix.
    base = random.choice(list(pool))
    suffix = 2
    while f"{base} {suffix}" in used:
        suffix += 1
    return f"{base} {suffix}"


def appliance_display_name(appliance) -> str | None:
    """Human-readable label; printers always include IP (or em dash if unset)."""
    if appliance is None:
        return None
    base = appliance.name or f"#{appliance.id}"
    if appliance.type == "printer":
        ip = (appliance.ip_address or "").strip() or "—"
        return f"{base} ({ip})"
    return base


def generate_appliance_name(
    db: Session,
    appliance_type: str,
    exclude_id: int | None = None,
) -> str | None:
    """Return an automatic name for server/printer types, else None."""
    used = _used_names(db, appliance_type, exclude_id)
    if appliance_type == "server":
        return _pick_from_pool(GREEK_GODS, used)
    if appliance_type == "printer":
        return _pick_from_pool(CAPITAL_CITIES, used)
    return None
