ROLE_PLATFORM_ADMIN = "platform_admin"
ROLE_TENANT_ADMIN = "tenant_admin"
ROLE_ORGANISATION_ADMIN = "organisation_admin"
ROLE_MEMBER = "member"

ALL_ROLES = (ROLE_PLATFORM_ADMIN, ROLE_TENANT_ADMIN, ROLE_ORGANISATION_ADMIN, ROLE_MEMBER)

ASSIGNABLE_BY_ORGANISATION_ADMIN = (ROLE_MEMBER, ROLE_ORGANISATION_ADMIN)

DEFAULT_HIRE_COMPANY_NAME = "Vendiqo"
